apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "employee-management.frontend.fullname" . }}-config
data:
  BACKEND_HOST: {{ include "employee-management.backend.fullname" . }}-service
  BACKEND_PORT: "{{ .Values.backend.service.port }}"
