apiVersion: v1
kind: Service

metadata:
  name: {{ include "employee-management.frontend.fullname" . }}-service

spec:
  selector:
    app: {{ include "employee-management.frontend.fullname" . }}

  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}

  type: ClusterIP
